# Generated by Django 5.0.6 on 2024-06-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='school',
            new_name='university',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='about',
            new_name='bio',
        ),
    ]
