# Generated by Django 5.0.6 on 2024-06-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_school_education_university_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='university',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_url',
            field=models.URLField(blank=True),
        ),
    ]
