# Generated by Django 5.0.6 on 2024-06-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkedinprofile",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="linkedinprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="linkedinprofile",
            name="linkedin_profile_url",
            field=models.URLField(),
        ),
    ]
