# Generated by Django 5.0.6 on 2024-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_linkedinprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkedinprofile",
            name="user",
            field=models.CharField(max_length=50),
        ),
    ]
