# Generated by Django 5.0.6 on 2024-06-05 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profilelinkedin_delete_linkedinprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilelinkedin",
            name="linkedin_profile_url",
        ),
    ]
